server:
  port: 9999

spring:
  application:
    name: bishevent

  datasource:
    url: jdbc:postgresql://localhost:5432/bishevent
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: opinion.techsupp@gmail.com
    password: xtdk zfst utei mtjj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true